name: Build & Deploy Sanity Studio
on:
  push:
    branches:
      -main
jobs:
  build-and-deploy:
   name: Build & Deploy Sanity Studio
   runs-on: ubuntu-latest
   steps:   
     -name: Checkout code
      uses: actions/checkout@v2
   -name: Install Node.js
    uses: actions/setup-node@v1
    with:
    node-version: node-version: '16.x'
   -name: Install Project Dependencies
     run: npm ci
     working-directory: ./portfolio/shivan-mahendrarajah-personal-website
    -name: Install Sanity CLI
     run: npm install -g @sanity/cli
    -name: Build Studio
     run: sanity build
     working-directory: ./portfolio/shivan-mahendrarajah-personal-website
    -name: Verify Build
     run: ls -la dist
     working-directory: ./portfolio/shivan-mahendrarajah-personal-website
    -name: Set Up SSH
     run: |
      mkdir -p ~/.ssh/
      echo "${{ secrets.SANITY_CMS_HOSTINGER_SSH_KEY }}"
      sudo chmod 600 ~/.ssh/sanity_cms
      ssh-keyscan -H "89.117.139.125" > ~/.ssh/known_hosts
    -name: SFTP Upload
     run: sftp  -p 65002 u533830657@89.117.139.125 <<< $'cd studio.mahendrarajah.com \n put -r studio/dist/*'

